// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eupbmemehrjezgwroeum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1cGJtZW1laHJqZXpnd3JvZXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzU4NDgsImV4cCI6MjA1ODI1MTg0OH0.4HGM8QAs9_aRH6r7biUHv9FvmSwW2nop7kQlPu3CQB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);